
package br.uniriotec.propid.rpc.noprop;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicoHelloNoPropService", targetNamespace = "http://br/uniriotec/propid/rpc/noprop", wsdlLocation = "http://localhost:7001/ServicoHelloNoPropRPC/ServicoHelloNoProp?WSDL")
public class ServicoHelloNoPropService
    extends Service
{

    private final static URL SERVICOHELLONOPROPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICOHELLONOPROPSERVICE_EXCEPTION;
    private final static QName SERVICOHELLONOPROPSERVICE_QNAME = new QName("http://br/uniriotec/propid/rpc/noprop", "ServicoHelloNoPropService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/ServicoHelloNoPropRPC/ServicoHelloNoProp?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOHELLONOPROPSERVICE_WSDL_LOCATION = url;
        SERVICOHELLONOPROPSERVICE_EXCEPTION = e;
    }

    public ServicoHelloNoPropService() {
        super(__getWsdlLocation(), SERVICOHELLONOPROPSERVICE_QNAME);
    }

    public ServicoHelloNoPropService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOHELLONOPROPSERVICE_QNAME);
    }

    public ServicoHelloNoPropService(URL wsdlLocation) {
        super(wsdlLocation, SERVICOHELLONOPROPSERVICE_QNAME);
    }

    public ServicoHelloNoPropService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOHELLONOPROPSERVICE_QNAME);
    }

    public ServicoHelloNoPropService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoHelloNoPropService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServicoHelloNoProp
     */
    @WebEndpoint(name = "ServicoHelloNoPropSoapPort")
    public ServicoHelloNoProp getServicoHelloNoPropSoapPort() {
        return super.getPort(new QName("http://br/uniriotec/propid/rpc/noprop", "ServicoHelloNoPropSoapPort"), ServicoHelloNoProp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoHelloNoProp
     */
    @WebEndpoint(name = "ServicoHelloNoPropSoapPort")
    public ServicoHelloNoProp getServicoHelloNoPropSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://br/uniriotec/propid/rpc/noprop", "ServicoHelloNoPropSoapPort"), ServicoHelloNoProp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOHELLONOPROPSERVICE_EXCEPTION!= null) {
            throw SERVICOHELLONOPROPSERVICE_EXCEPTION;
        }
        return SERVICOHELLONOPROPSERVICE_WSDL_LOCATION;
    }

}
