
package br.uniriotec.propid.rpc.noprop;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicoHelloNoProp", targetNamespace = "http://br/uniriotec/propid/rpc/noprop")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoHelloNoProp {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://br/uniriotec/propid/rpc/noprop")
    @RequestWrapper(localName = "hello", targetNamespace = "http://br/uniriotec/propid/rpc/noprop", className = "br.uniriotec.propid.rpc.noprop.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://br/uniriotec/propid/rpc/noprop", className = "br.uniriotec.propid.rpc.noprop.HelloResponse")
    public String hello();

}
