
package br.uniriotec.propid.rpc.prop;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicoHello", targetNamespace = "http://br/uniriotec/propid")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoHello {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://br/uniriotec/propid")
    @RequestWrapper(localName = "hello", targetNamespace = "http://br/uniriotec/propid", className = "br.uniriotec.propid.rpc.prop.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://br/uniriotec/propid", className = "br.uniriotec.propid.rpc.prop.HelloResponse")
    public String hello();

}
