
package br.uniriotec.propid.rpc.prop;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicoHelloService", targetNamespace = "http://br/uniriotec/propid", wsdlLocation = "http://localhost:7001/ServicoHelloPropRPC/ServicoHello?WSDL")
@HandlerChain(file="handlerchain.xml")
public class ServicoHelloService
    extends Service
{

    private final static URL SERVICOHELLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICOHELLOSERVICE_EXCEPTION;
    private final static QName SERVICOHELLOSERVICE_QNAME = new QName("http://br/uniriotec/propid", "ServicoHelloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/ServicoHelloPropRPC/ServicoHello?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOHELLOSERVICE_WSDL_LOCATION = url;
        SERVICOHELLOSERVICE_EXCEPTION = e;
    }

    public ServicoHelloService() {
        super(__getWsdlLocation(), SERVICOHELLOSERVICE_QNAME);
    }

    public ServicoHelloService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOHELLOSERVICE_QNAME);
    }

    public ServicoHelloService(URL wsdlLocation) {
        super(wsdlLocation, SERVICOHELLOSERVICE_QNAME);
    }

    public ServicoHelloService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOHELLOSERVICE_QNAME);
    }

    public ServicoHelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoHelloService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServicoHello
     */
    @WebEndpoint(name = "ServicoHelloSoapPort")
    public ServicoHello getServicoHelloSoapPort() {
        return super.getPort(new QName("http://br/uniriotec/propid", "ServicoHelloSoapPort"), ServicoHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoHello
     */
    @WebEndpoint(name = "ServicoHelloSoapPort")
    public ServicoHello getServicoHelloSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://br/uniriotec/propid", "ServicoHelloSoapPort"), ServicoHello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOHELLOSERVICE_EXCEPTION!= null) {
            throw SERVICOHELLOSERVICE_EXCEPTION;
        }
        return SERVICOHELLOSERVICE_WSDL_LOCATION;
    }

}
